title: Fyrypt
logo: https://mirfatif.github.io/mirfatif/logos/fyrypt.png
description: Android Firewall, dnscrypt-proxy manager, and network monitor
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
